### ISSUE TITLE
Error `/bin/bash: line 1: 28911 Aborted lua-format -i 2> /tmp/nvimt20t1k/5`

### ISSUE THREAD

**Issue by luisiacc** [andrejlevkovitch/vim-lua-format#5]
Got this error when doing `:call LuaFormat()`:

```
/bin/bash: line 1: 28911 Aborted lua-format -i 2> /tmp/nvimt20t1k/5
```
It replaces the content of the file where it's applied.

Neovim version:
```
NVIM v0.6.0-dev+521-g615e03c33
Build type: Release
LuaJIT 2.1.0-beta3
```

OS: Ubuntu 18.04

**Comment by andrejlevkovitch** [comment]
Hi! Thank for your report. Could you provide information from error log file? In your case `/tmp/nvimt20t1k/5` is an error log file

**Comment by luisiacc** [comment]
Sry, when I check in the `nvimt20t1k`(or whatever name has at the time it shows the error) folder, no `5` file is there.

**Comment by andrejlevkovitch** [comment]
Sorry, my fault: it is temp file, so I display information in `lwindow` and remove error file. Could you, please, comment [this line](https://github.com/andrejlevkovitch/vim-lua-format/blob/cb07a86f665bd552b4e103f99dd68f97b49bd045/autoload/lua_format.vim#L69) (comment in vimscript is `"`)

**Comment by luisiacc** [comment]
Here you got: 
```
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory
```

**Comment by andrejlevkovitch** [comment]
Intersting. Could you provide tree of your directory and rights for files in that directory?

**Comment by luisiacc** [comment]
Actually it happens on any lua file, I tried opening nvim with `sudo` but got the same error, anyways here is an example, I just created a lua file and tried to format it.

File structure:
```
total 20
-rw-r--r-- 1 acc acc 1365 Nov  3 10:55 README.md
-rw-r--r-- 1 acc acc   44 Nov 12 15:08 asd.lua
drwxr-xr-x 2 acc acc 4096 May 22 18:10 autoload
drwxr-xr-x 2 acc acc 4096 May 22 18:10 plugin
```

lua file `asd.lua`:
```lua
local theme = {
    full = 1,
amer = "2",
}

```

**Comment by andrejlevkovitch** [comment]
I think that your problem related to this part of code:

https://github.com/Koihik/LuaFormatter/blob/7c27bab3b7cd4ab0bae0f8d52336a093b5da307b/src/main.cpp#L399-L415

Assume that you didn't create `.lua-format` file - this file need for provide configuration different, then default. I also try search this file in the plugin:

https://github.com/andrejlevkovitch/vim-lua-format/blob/cb07a86f665bd552b4e103f99dd68f97b49bd045/autoload/lua_format.vim#L43-L46

because previous versions of LuaFormat didn't support recursive searching of config file.

I assume that you have some permission problem for one of parent directories. But anyway you should report about the problem to [LuaFormat project](https://github.com/Koihik/LuaFormatter)

**Comment by andrejlevkovitch** [comment]
> File structure:
>
>total 20
>-rw-r--r-- 1 acc acc 1365 Nov  3 10:55 README.md
>-rw-r--r-- 1 acc acc   44 Nov 12 15:08 asd.lua
>drwxr-xr-x 2 acc acc 4096 May 22 18:10 autoload
>drwxr-xr-x 2 acc acc 4096 May 22 18:10 plugin


Also, please, provide structure and permissions of parent directories - it could help for locating the problem

**Comment by luisiacc** [comment]
Okk seems like you are correct, if I create a `.lua-format` file on the same folder as the `asd.lua` file, then it formats correctly. Thank you for the help!
